services:
  postgres:
    build:
      context: .
      dockerfile: ./nsk_postgres/Dockerfile
    restart: on-failure
    container_name: nsk_postgres
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=nsk
      - POSTGRES_USER=handalab
      - POSTGRES_PASSWORD=handalab
    volumes:
      - ./nsk_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./nsk_postgres/data:/var/lib/postgresql/data

